import os

DOMINO_API_SERVER = "https://test.com"
DOMINO_API_SERVER_VERIFY_SSL = False

# Expects s3://<bucket name>
EXPORTS_PROJECT_FILES_S3_BUCKET = "s3://domino-export"

# Available Variables: S3_BUCKET, EXPORT_GROUP_NAME, EXPORT_PROJECT_NAME, DOMINO_USERNAME, DOMINO_PROJECT_NAME
EXPORTS_PROJECT_FILES_S3_PATH_FORMAT = "{S3_BUCKET}/projects/{EXPORT_GROUP_NAME}/{EXPORT_PROJECT_NAME}"
# In addition to the above variables, you can also reference EXPORTS_PROJECT_FILES_S3_PATH as well for the following two formats
EXPORTS_PROJECT_FILES_S3_LATEST_FORMAT = "{EXPORTS_PROJECT_FILES_S3_PATH}/latest"
EXPORTS_PROJECT_FILES_S3_PRIOR_FORMAT = "{EXPORTS_PROJECT_FILES_S3_PATH}/prior"
EXPORTS_PROJECT_FILES_S3_SYNC_LOG_PATH_FORMAT = "{EXPORTS_PROJECT_FILES_S3_PATH}/sync-status.log"
EXPORTS_PROJECT_FILES_S3_SYNC_LOG_MAX_RECORDS = 10

# Leave as none for the export service to automatically discover
DOMINO_DOCKER_REGISTRY = "XYZ.dkr.ecr.us-east-1.amazonaws.com/domino-export"
# Set these to None if you want to use the cached credentials
DOMINO_DOCKER_REGISTRY_USER = "AWS"
DOMINO_DOCKER_REGISTRY_PASSWORD = os.environ["ECR_KEY"]
# DEBUG PURPOSES
DOMINO_DOCKER_IMAGE_FORMAT = "{DOCKER_REGISTRY}:{DOMINO_COMPUTE_ENVIRONMENT_ID}-v{DOMINO_COMPUTE_ENVIRONMENT_REVISION}"

EXPORTS_DOCKER_REGISTRY = "XYZ.dkr.ecr.us-east-1.amazonaws.com/domino-export"
# Set these to None if you want to use the cached, system credentials
EXPORTS_DOCKER_REGISTRY_USERNAME = "AWS"
EXPORTS_DOCKER_REGISTRY_PASSWORD = os.environ["ECR_KEY"]

# Available Variables: DOCKER_REGISTRY, EXPORT_GROUP_NAME, EXPORT_PROJECT_NAME, DOMINO_USERNAME, DOMINO_PROJECT_NAME, DOMINO_COMPUTE_ENVIRONMENT_ID, DOMINO_COMPUTE_ENVIRONMENT_REVISION
EXPORTS_DOCKER_IMAGE_NAME_VERSION_FORMAT = "{DOCKER_REGISTRY}:{EXPORT_GROUP_NAME}-{EXPORT_PROJECT_NAME}-{DOMINO_COMPUTE_ENVIRONMENT_ID}-v{DOMINO_COMPUTE_ENVIRONMENT_REVISION}"
EXPORTS_DOCKER_IMAGE_NAME_LATEST_FORMAT = "{DOCKER_REGISTRY}:{EXPORT_GROUP_NAME}-{EXPORT_PROJECT_NAME}-latest"

JOBS_MAX_CONCURRENT_WORKERS = 3
EXPORT_JOB_SCHEDULE_DEFAULT_FREQUENCY_SECONDS = 15
EXPORTS_PROJECT_FILES_S3_TOP_LEVEL_LOG_FREQUENCY_SECONDS = 20

DATABASE_PRUNE_FREQUENCY_SECONDS = 10
DATABASE_HISTORY_AGE_DAYS = 1
